language: node_js
node_js:
    - "0.10.26"
before_install:
    - npm install -g gulp
    - npm install
    - npm install -g bower
    - bower install
    - apt-get install -qq google-chrome
script:
    - gulp test
notifications:
  email:
    recipients:
      - jespinog@gmail.com
      - andrei.antoukh@gmail.com
      - bameda@dbarragan.com
      - anler86@gmail.com
    on_success: change
    on_failure: change
