language: node_js
node_js:
    - "0.10.26"
install:
    - sudo npm install -g gulp
    - npm install
    - sudo npm install -g bower
    - bower install
script:
    - gulp test
notifications:
  email:
    recipients:
      - jespinog@gmail.com
      - andrei.antoukh@gmail.com
      - bameda@dbarragan.com
      - anler86@gmail.com
    on_success: change
    on_failure: change
